import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { comfortStats, parseVelocityCsv } from "../comfort.js";
import { exportGeometry, runCommand, type SimCase, type SolverAdapter } from "../store.js";
import { findAnsysRoot, workbenchExecutable } from "./ansys.js";

/** Python literal (IronPython 2.7) for a JSON-compatible value. */
export function pyLiteral(v: unknown): string {
  if (v === null || v === undefined) return "None";
  if (typeof v === "boolean") return v ? "True" : "False";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "None";
  if (typeof v === "string") return `u${JSON.stringify(v)}`;
  if (Array.isArray(v)) return `[${v.map(pyLiteral).join(", ")}]`;
  return `{${Object.entries(v as object).map(([k, x]) => `u${JSON.stringify(k)}: ${pyLiteral(x)}`).join(", ")}}`;
}

/**
 * Workbench batch journal (IronPython, run by RunWB2 -B -R): open the project, replace the
 * geometry file, set the input parameters, update all systems, write every parameter value.
 */
export function workbenchJournal(job: {
  project: string;
  geometry?: string;
  system: string;
  component: string;
  parameters: Record<string, unknown>;
  dir: string;
  save_project: boolean;
}): string {
  return `# -*- coding: utf-8 -*-
# Journal generated by the "Fusion Rhino Grasshopper ANSYS" connector.
# Run: RunWB2.exe -B -R run.wbjn   (Workbench batch mode)
import os
case = ${pyLiteral(job)}
log = open(os.path.join(case["dir"], "workbench_log.txt"), "w")
def write(message):
    log.write(str(message) + "\\n")
    log.flush()
try:
    Open(FilePath=case["project"])
    write("project opened: " + case["project"])
    if case["geometry"]:
        system = GetSystem(Name=case["system"])
        container = system.GetContainer(ComponentName=case["component"])
        container.SetFile(FilePath=case["geometry"])
        write("geometry replaced: " + case["geometry"])
    for name in case["parameters"]:
        parameter = Parameters.GetParameter(Name=name)
        parameter.Expression = str(case["parameters"][name])
        write("parameter %s = %s" % (name, case["parameters"][name]))
    Update()
    write("project updated")
    out = open(os.path.join(case["dir"], "results.txt"), "w")
    for parameter in Parameters.GetAllParameters():
        try:
            out.write("%s\\t%s\\t%s\\n" % (parameter.Name, parameter.DisplayText, parameter.Value))
        except Exception as error:
            write("cannot read %s: %s" % (parameter.Name, error))
    out.close()
    if case["save_project"]:
        Save(Overwrite=True)
        write("project saved")
    write("done")
except Exception as error:
    write("ERROR: %s" % error)
    raise
finally:
    log.close()
`;
}

/** Parses results.txt lines "P3<TAB>Max Velocity<TAB>4.2 [m s^-1]" into metrics (by id and by name). */
export function parseWorkbenchResults(text: string): { metrics: Record<string, number>; parameters: Array<{ id: string; name: string; value: string }> } {
  const metrics: Record<string, number> = {};
  const parameters: Array<{ id: string; name: string; value: string }> = [];
  for (const line of text.split(/\r?\n/)) {
    const [id, name, value] = line.split("\t");
    if (!id || value === undefined) continue;
    parameters.push({ id, name, value });
    const n = Number(/^\s*([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)/.exec(value)?.[1]);
    if (!Number.isFinite(n)) continue;
    metrics[id] = n;
    const key = name.trim().replace(/[^\p{L}\p{N}]+/gu, "_").replace(/^_|_$/g, "");
    if (key) metrics[key] = n;
  }
  return { metrics, parameters };
}

/**
 * Drives an existing, validated ANSYS Workbench project (any physics: Fluent wind, Mechanical,
 * thermal, Icepak…): the variant geometry replaces the project's geometry file, the design
 * parameters are pushed to the Workbench input parameters, the project is updated in batch,
 * and every output parameter comes back as a metric.
 */
export const workbenchAdapter: SolverAdapter = {
  id: "ansys_workbench",
  title: "ANSYS Workbench (projet paramétré existant)",
  description:
    "Met à jour un projet Workbench .wbpj déjà validé : remplace la géométrie par celle de la variante (STEP/STL…), " +
    "renseigne les paramètres d'entrée, lance la mise à jour en mode batch et récupère les paramètres de sortie.",
  settings: {
    project: "Chemin du projet Workbench .wbpj (obligatoire)",
    geometry: "Géométrie à exporter: {layer|ids|filter|grasshopper} (facultatif)",
    geometry_format: "Extension du fichier géométrie: step (défaut), stp, igs, x_t, stl, 3dm",
    system: "Nom du système Workbench qui porte la géométrie (défaut SYS)",
    component: "Composant géométrie (défaut Geometry)",
    parameters: "Paramètres Workbench {\"P1\": 18, \"P2\": \"{Building_Height}\"}: {nom} reprend un paramètre de la variante",
    save_project: "Enregistrer le projet après mise à jour (défaut false)",
    velocity_csv: "Fichier x,y,z,vitesse exporté par le projet (vent au niveau piéton) → métriques de confort Lawson",
    reference_speed: "Vitesse de référence du vent simulé (m/s) pour les ratios de vitesse",
    ansys_root: "Dossier ANSYS (ex. C:\\Program Files\\ANSYS Inc\\v242) si non détecté",
    timeout_minutes: "Durée maximale (défaut 240)",
  },

  async check(_ctx, settings) {
    const found = findAnsysRoot(settings?.ansys_root);
    if (!found.root) return { available: false, detail: `ANSYS non trouvé (variables AWP_ROOTxxx absentes). Candidats: ${found.candidates.join(", ") || "aucun"}` };
    const exe = workbenchExecutable(found.root);
    return fs.existsSync(exe) ? { available: true, detail: `Workbench ${found.version ?? ""}: ${exe}` } : { available: false, detail: `RunWB2 introuvable: ${exe}` };
  },

  async prepare(ctx, c: SimCase) {
    const s = c.settings;
    if (!s.project) throw new Error("'project' (.wbpj) is required.");
    let geometry: string | undefined;
    if (s.geometry) {
      const ext = String(s.geometry_format ?? "step").replace(/^\./, "");
      geometry = await exportGeometry(ctx, s.geometry, path.join(c.dir, `geometry.${ext}`));
      c.inputs.geometry = path.basename(geometry);
    }
    const params: Record<string, unknown> = {};
    const variantParams: Record<string, unknown> = s._variant_parameters ?? {};
    for (const [k, v] of Object.entries(s.parameters ?? {})) {
      const ref = typeof v === "string" ? /^\{(.+)\}$/.exec(v.trim()) : null;
      if (ref) {
        if (!(ref[1] in variantParams)) throw new Error(`Parameter '${k}' refers to '{${ref[1]}}' which is not a variant parameter.`);
        params[k] = variantParams[ref[1]];
      } else params[k] = v;
    }
    const journal = workbenchJournal({
      project: path.resolve(s.project),
      geometry: geometry ? path.resolve(geometry) : undefined,
      system: s.system ?? "SYS",
      component: s.component ?? "Geometry",
      parameters: params,
      dir: path.resolve(c.dir),
      save_project: Boolean(s.save_project),
    });
    await fsp.writeFile(path.join(c.dir, "run.wbjn"), journal, "utf8");
    c.inputs.journal = "run.wbjn";
    const found = findAnsysRoot(s.ansys_root);
    const exe = found.root ? workbenchExecutable(found.root) : "RunWB2.exe";
    c.command = [exe, "-B", "-R", path.join(c.dir, "run.wbjn")];
  },

  async run(ctx, c, h) {
    await runCommand(c, h, Number(c.settings.timeout_minutes ?? 240) * 60000);
  },

  async collect(_ctx, c) {
    const file = path.join(c.dir, "results.txt");
    if (!fs.existsSync(file)) throw new Error("Workbench wrote no results.txt: see workbench_log.txt and run.log in the case folder.");
    const { metrics, parameters } = parseWorkbenchResults(await fsp.readFile(file, "utf8"));
    c.metrics = metrics;
    c.results = { parameters };
    await collectWindComfort(c);
  },
};

/** Pedestrian wind comfort from a velocity export (shared by the Workbench and command adapters). */
export async function collectWindComfort(c: SimCase): Promise<void> {
  const rel = c.settings.velocity_csv;
  if (!rel) return;
  const file = path.isAbsolute(rel) ? rel : path.join(c.dir, rel);
  if (!fs.existsSync(file)) {
    (c.warnings ??= []).push(`velocity_csv not found: ${file}`);
    return;
  }
  const samples = parseVelocityCsv(await fsp.readFile(file, "utf8"));
  const stats = comfortStats(samples, Number(c.settings.reference_speed ?? 0), Number(c.settings.cell_area ?? 1));
  c.metrics = {
    ...(c.metrics ?? {}),
    wind_mean_speed: stats.mean_speed,
    wind_p95_speed: stats.p95_speed,
    wind_max_speed: stats.max_speed,
    wind_pct_sitting: stats.area_pct.sitting,
    wind_pct_uncomfortable: stats.area_pct.uncomfortable,
    ...(stats.mean_speed_ratio !== null ? { wind_mean_speed_ratio: stats.mean_speed_ratio } : {}),
  };
  c.results = { ...((c.results as object) ?? {}), wind_comfort: stats };
}
